//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realty.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.ImageApartment = new HashSet<ImageApartment>();
            this.RentApartment = new HashSet<RentApartment>();
            this.SaleApartment = new HashSet<SaleApartment>();
        }
    
        public int IDApartment { get; set; }
        public string NumberHouse { get; set; }
        public int IDStreet { get; set; }
        public string Description { get; set; }
        public bool ForRent { get; set; }
        public int NumberApartment { get; set; }
        public decimal Cost { get; set; }
        public int QtyFloor { get; set; }
        public int QtyRoom { get; set; }
        public double Space { get; set; }
        public bool HasBalcony { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Street Street { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageApartment> ImageApartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentApartment> RentApartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleApartment> SaleApartment { get; set; }
    }
}
