//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realty.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public House()
        {
            this.ImageHouse = new HashSet<ImageHouse>();
            this.RentHouse = new HashSet<RentHouse>();
            this.SaleHouse = new HashSet<SaleHouse>();
        }
    
        public int IDHouse { get; set; }
        public string NumberHouse { get; set; }
        public int IDStreet { get; set; }
        public string Description { get; set; }
        public bool ForRent { get; set; }
        public decimal Cost { get; set; }
        public int QtyFloor { get; set; }
        public int QtyRoom { get; set; }
        public double Space { get; set; }
        public double SpaceArea { get; set; }
        public bool HasPool { get; set; }
        public bool HasBath { get; set; }
        public bool HasPlumbing { get; set; }
        public bool HasGas { get; set; }
        public bool HasElectricity { get; set; }
        public bool Isdelete { get; set; }
    
        public virtual Street Street { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageHouse> ImageHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentHouse> RentHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleHouse> SaleHouse { get; set; }
    }
}
