//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realty.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageHouse
    {
        public int IDImageHouse { get; set; }
        public byte[] Image { get; set; }
        public int IDHouse { get; set; }
    
        public virtual House House { get; set; }
    }
}
