//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realty.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealttyEntities : DbContext
    {
        public RealttyEntities()
            : base("name=RealttyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<ImageApartment> ImageApartment { get; set; }
        public virtual DbSet<ImageHouse> ImageHouse { get; set; }
        public virtual DbSet<NumberHouse> NumberHouse { get; set; }
        public virtual DbSet<RentApartment> RentApartment { get; set; }
        public virtual DbSet<RentHouse> RentHouse { get; set; }
        public virtual DbSet<SaleApartment> SaleApartment { get; set; }
        public virtual DbSet<SaleHouse> SaleHouse { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Adress> Adress { get; set; }
    }
}
