//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realty.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumberHouse
    {
        public int IDNumHouse { get; set; }
        public string Number { get; set; }
        public int IDStreet { get; set; }
    }
}
