//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realty.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleApartment
    {
        public int IDSaleApartment { get; set; }
        public int IDApartment { get; set; }
        public int IDCLient { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Client Client { get; set; }
    }
}
