//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realty.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleHouse
    {
        public int IDSaleHouse { get; set; }
        public Nullable<int> IDHouse { get; set; }
        public int IDClient { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual House House { get; set; }
    }
}
